### ISSUE TITLE
Storage permission request for mobile apk

### ISSUE THREAD

**Issue by johnd0e** [IITC-CE/ingress-intel-total-conversion#4]
On start I've got only 1 permisson request: Location.
And there were no request about Storage access which is necessary e.g. for external plugins.

I was able to set the permission manually but it will be better if it requested on apk start.

**Comment by johnd0e** [comment]
https://github.com/iitc-project/ingress-intel-total-conversion/pull/1286/commits/154e1bca058ff6dfd37a56dcfc72013329e915c7

**Comment by modos189** [comment]
done

**Comment by johnd0e** [comment]
There are still some issues with it.
I successfully set the permission and can access user scripts, but on every launch I still see the toast `Permissions are required if you want to use user scripts or cache on SDCard`.

**Comment by modos189** [comment]
Request write storage permissions only if you add scripts. Saving the tile cache does not require additional permissions. https://github.com/IITC-CE/ingress-intel-total-conversion/commit/cdb7e89c47a53e4e991051d11b4461117fd1407c

**Comment by johnd0e** [comment]
> Request write storage permissions only if you add scripts.

When I open *.user.js at Chrome webpage (or in file manager) it proposes list of applications.
I select IITC and after confirmation all seems ok, but then `Plugins settings` screen appears without user plugins.

There should be permission request, I suppose.

And I think this even will not be enough, consider this case:
IITC was once installed and we have user plugins in `IITC-Mobile/plugins` directory.
Then we uninstall apk, and install it again.
Will we get permission request?
